import { CurriculumDTO, LearningLevelDTO, TopicDTO } from "@/lib/api";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ExternalLink } from "lucide-react";

export function CurriculumBreakdown({ curriculum }: { curriculum: CurriculumDTO }) {
  const renderTopics = (topics: TopicDTO[], level: number = 0) => {
    return topics.map((topic) => (
      <AccordionItem value={topic.id} key={topic.id}>
        <AccordionTrigger className={`text-left ${level === 0 ? 'font-semibold text-base' : 'text-sm'}`}>
          <div className="flex justify-between items-center w-full pr-4">
            <span>{topic.order}. {topic.title}</span>
            {topic.estimated_hours > 0 && (
              <Badge variant="outline" className="ml-2 whitespace-nowrap">{topic.estimated_hours} hrs</Badge>
            )}
          </div>
        </AccordionTrigger>
        <AccordionContent className="pl-4">
          <p className="text-sm text-muted-foreground mb-2">{topic.description}</p>
          {topic.outcomes && topic.outcomes.length > 0 && (
            <div className="mb-2">
              <span className="font-medium text-xs text-muted-foreground">Outcomes: </span>
              <div className="flex flex-wrap gap-1 mt-1">
                {topic.outcomes.map((outcome, idx) => <Badge key={idx} variant="secondary" className="px-2 py-0.5 text-xs">{outcome}</Badge>)}
              </div>
            </div>
          )}
           {topic.example_exercises && topic.example_exercises.length > 0 && (
            <div className="mb-2">
              <span className="font-medium text-xs text-muted-foreground">Exercises: </span>
              <div className="flex flex-wrap gap-1 mt-1">
                {topic.example_exercises.map((exercise, idx) => <Badge key={idx} variant="outline" className="px-2 py-0.5 text-xs">{exercise}</Badge>)}
              </div>
            </div>
          )}
          {topic.helpful_references && topic.helpful_references.length > 0 && (
            <div className="mb-2">
              <span className="font-medium text-xs text-muted-foreground">References: </span>
              <div className="flex flex-wrap gap-1 mt-1">
                {topic.helpful_references.map((ref, idx) => (
                    <a href={ref.url} target="_blank" rel="noopener noreferrer" key={idx} className="flex items-center text-blue-500 hover:underline text-xs">
                        {ref.sourceId} <ExternalLink className="ml-1 h-3 w-3" />
                    </a>
                ))}
              </div>
            </div>
          )}
          {topic.subtopics && topic.subtopics.length > 0 && (
            <div className="pl-4 border-l ml-2 mt-2">
              <Accordion type="multiple" className="w-full">
                {renderTopics(topic.subtopics, level + 1)}
              </Accordion>
            </div>
          )}
        </AccordionContent>
      </AccordionItem>
    ));
  };

  return (
    <div className="mb-8">
      <h2 className="text-2xl font-bold mb-4">Curriculum Breakdown</h2>
      <p className="text-sm text-muted-foreground mb-4">
        Structured path from Beginner to Expert, with estimated hours per level and key topics.
        (Generated by {curriculum.model_version} at {new Date(curriculum.generated_at).toLocaleString()})
      </p>

      <div className="space-y-6">
        {curriculum.overall_learning_path.map((levelData: LearningLevelDTO) => (
          <Card key={levelData.level}>
            <CardHeader>
              <CardTitle className="flex justify-between items-center">
                <span>{levelData.level}</span>
                <Badge className="bg-blue-500 text-white">{levelData.estimated_hours} hrs est.</Badge>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Accordion type="multiple" className="w-full">
                {renderTopics(levelData.topics)}
              </Accordion>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
